# Generated by Django 2.1.7 on 2019-03-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190323_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient'),
        ),
    ]
